export default [
  {
    id: "1",
    date: "20202212",
    invoiceNumber: 1,
    customerName: "xyz",
    billingAddress: "xyz",
    shippingAdderess: "xyz",
    gstin: "123124",
    items: {
      id: "1",
      itemName: "abc",
      quantity: "3",
      price: 50,
      amount: 56,
    },
    billSundrys: {
      id: "2",
      billSundryName: "sdsad",
      amount: "30",
    },
  },
  {
    id: "2",
    date: "20202212",
    invoiceNumber: 1,
    customerName: "xyz",
    billingAddress: "xyz",
    shippingAdderess: "xyz",
    gstin: "123124",
    items: {
      id: "1",
      itemName: "abc",
      quantity: "3",
      price: 50,
      amount: 56,
    },
    billSundrys: {
      id: "2",
      billSundryName: "sdsad",
      amount: "30",
    },
  },
  {
    id: "3",
    date: "20202212",
    invoiceNumber: 1,
    customerName: "xyz",
    billingAddress: "xyz",
    shippingAdderess: "xyz",
    gstin: "123124",
    items: {
      id: "1",
      itemName: "abc",
      quantity: "3",
      price: 50,
      amount: 56,
    },
    billSundrys: {
      id: "2",
      billSundryName: "sdsad",
      amount: "30",
    },
  },
  {
    id: "4",
    date: "20202212",
    invoiceNumber: 1,
    customerName: "xyz",
    billingAddress: "xyz",
    shippingAdderess: "xyz",
    gstin: "123124",
    items: {
      id: "1",
      itemName: "abc",
      quantity: "3",
      price: 50,
      amount: 56,
    },
    billSundrys: {
      id: "2",
      billSundryName: "sdsad",
      amount: "30",
    },
  },
  {
    id: "5",
    date: "20202212",
    invoiceNumber: 1,
    customerName: "xyz",
    billingAddress: "xyz",
    shippingAdderess: "xyz",
    gstin: "123124",
    items: {
      id: "1",
      itemName: "abc",
      quantity: "3",
      price: 50,
      amount: 56,
    },
    billSundrys: {
      id: "2",
      billSundryName: "sdsad",
      amount: "30",
    },
  },
  {
    id: "6",
    date: "20202212",
    invoiceNumber: 1,
    customerName: "xyz",
    billingAddress: "xyz",
    shippingAdderess: "xyz",
    gstin: "123124",
    items: {
      id: "1",
      itemName: "abc",
      quantity: "3",
      price: 50,
      amount: 56,
    },
    billSundrys: {
      id: "2",
      billSundryName: "sdsad",
      amount: "30",
    },
  },
]